# Generated by Django 3.2.15 on 2022-08-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiloV1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pacote', models.CharField(max_length=50)),
                ('dados_pacote', models.CharField(max_length=10000)),
            ],
        ),
    ]
