# Generated by Django 3.2.15 on 2022-08-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termometriaV1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecHorimetros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEquipamento', models.IntegerField(verbose_name=11)),
                ('dataHora', models.DateTimeField()),
                ('horasVent', models.IntegerField(verbose_name=11)),
                ('minutosVent', models.IntegerField(verbose_name=11)),
                ('horasDescarga', models.IntegerField(verbose_name=11)),
                ('minutosDescarga', models.IntegerField(verbose_name=11)),
                ('horasAspiracao', models.IntegerField(verbose_name=11)),
                ('minutosAspiracao', models.IntegerField(verbose_name=11)),
                ('horasAlimQueim', models.IntegerField(verbose_name=11)),
                ('minutosAlimQueim', models.IntegerField(verbose_name=11)),
                ('dtUltLimpezaPeriodica', models.DateTimeField()),
                ('dtUltEqualizDesc', models.DateTimeField()),
            ],
        ),
    ]
