# Generated by Django 3.2.15 on 2022-08-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termometriaV1', '0002_sechorimetros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sechorimetros',
            name='dataHora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sechorimetros',
            name='dtUltEqualizDesc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sechorimetros',
            name='dtUltLimpezaPeriodica',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sechorimetros',
            name='horasAlimQueim',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sechorimetros',
            name='horasAspiracao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sechorimetros',
            name='horasDescarga',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sechorimetros',
            name='horasVent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sechorimetros',
            name='idEquipamento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sechorimetros',
            name='minutosAlimQueim',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sechorimetros',
            name='minutosAspiracao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sechorimetros',
            name='minutosDescarga',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sechorimetros',
            name='minutosVent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
