# Generated by Django 3.2.15 on 2022-09-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('termometriaV1', '0003_auto_20220831_1323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecHorimetros',
        ),
    ]
