# Generated by Django 3.2.15 on 2022-09-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecHorimetros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEquipamento', models.IntegerField(blank=True, null=True)),
                ('dataHora', models.DateTimeField(blank=True, null=True)),
                ('horasVent', models.IntegerField(blank=True, null=True)),
                ('minutosVent', models.IntegerField(blank=True, null=True)),
                ('horasDescarga', models.IntegerField(blank=True, null=True)),
                ('minutosDescarga', models.IntegerField(blank=True, null=True)),
                ('horasAspiracao', models.IntegerField(blank=True, null=True)),
                ('minutosAspiracao', models.IntegerField(blank=True, null=True)),
                ('horasAlimQueim', models.IntegerField(blank=True, null=True)),
                ('minutosAlimQueim', models.IntegerField(blank=True, null=True)),
                ('dtUltLimpezaPeriodica', models.DateTimeField(blank=True, null=True)),
                ('dtUltEqualizDesc', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
